import './js/mob-menu';
import './js/hero-title-typing';
import './js/counter';
import './js/buy-now';
import './js/products-modals';
import './js/how-made';
import './js/locations';
import './js/franchise';
import './js/slider';
import './js/on-scroll-animation'
